name: "Modrinth Description"

on:
 push:
   branches:
   - 1.21.10
  
jobs:
  modrinth-desc:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v5
    - uses: funnyboy-roks/modrinth-auto-desc@v1.7
      with:
        auth-token: ${{ secrets.MODRINTH_TOKEN }}
        slug: $SLUG
